first attempt (#1)
* first attempt

* run basic tests

* run basic tests part 2

* run basic tests part 3

* run basic tests part 4

* run basic tests part 5

* run basic tests part 6

* run basic tests part 7

* run basic tests part 8

* run basic tests part 9

* run basic tests part 9

* run basic tests part 10

* run basic tests part 11

* run basic tests part 12

* run basic tests part 13

* run basic tests part 14

* run basic tests part 15

* run basic tests part 16

* run basic tests part 17

* run basic tests part 18

* run basic tests part 19

* run basic tests part 20

* run basic tests part 21

* run basic tests part 22

* run basic tests part 23

* run basic tests part 24

* run basic tests part 26

* run basic tests part 27

* run basic tests part 28

* rework readme and add some options tests

* rework readme and add some options tests part 2

* rework readme and add some options tests part 3

* rework readme and add some options tests part 4

* rework readme and add some options tests part 5

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -6,7 +6,7 @@ branding:
 inputs:
   # Required
   leia-test:
-    description: "The Leia test file to run"
+    description: "The Leia test file to parse and run."
     required: true
 
   # Optional
@@ -45,29 +45,56 @@ runs:
     - name: Validate required inputs
       shell: bash
       run: |
-        echo "::group::No test file specified!"
         if [ "${{ inputs.leia-test }}" == "" ]; then
           echo "::error title=leia-test is not set!::You must specify a test file to parse and run."
           exit 10
         fi
-        echo "::endgroup::"
+
+        if [ ! -f "${{ inputs.leia-test }}" ]; then
+          echo "::error title=Could not find ${{ inputs.leia-test }}!::${{ inputs.leia-test }} does not seem to exist."
+          exit 11
+        fi
 
     - name: Install node 16
       uses: actions/setup-node@v3
       with:
         node-version: 16
         cache: npm
-
+    - name: Add local bin to PATH
+      shell: bash
+      run: echo "$GITHUB_WORKSPACE/node_modules/.bin" >> $GITHUB_PATH
     - name: Ensure Leia is installed
       shell: bash
       run: |
-        if ! "$GITHUB_WORKSPACE/node_modules/.bin/leia" --version >/dev/null; then
-          npm --global @lando/leia@${{ inputs.version }}
+        if ! leia --version &>/dev/null; then
+          echo "::group::Globally installing @lando/leia@${{ inputs.version }}"
+          npm install --global @lando/leia@${{ inputs.version }}
+          echo "::endgroup::"
         fi
 
-        if leia --version >/dev/null; then
-          echo "::notice title=Leia installed!::Using version $(leia --version) at $(which leia)"
-        else
+        if ! leia --version &>/dev/null; then
           echo "::error title=Cannot run leia::Cannot seem to find the Leia binary!"
           exit 11
         fi
+    - name: Run Leia tests
+      shell: bash
+      run: |
+        echo "::group::Leia information"
+          echo "bin: $(which leia)"
+          echo "version: $(leia --version)"
+        echo "::endgroup::"
+
+        OPTS=
+        if [ "${{ inputs.stdin }}" == "true" ]; then
+          OPTS="--stdin"
+        fi
+        if [ "${{ inputs.debug }}" == "true" ]; then
+          OPTS="$OPTS --debug"
+        fi
+
+        leia ${{ inputs.leia-test }} \
+          --setup-header="${{ inputs.setup-header }}" \
+          --test-header="${{ inputs.test-header }}" \
+          --cleanup-header="${{ inputs.cleanup-header }}" \
+          --retry=${{ inputs.retry }} $OPTS
+
